### ISSUE TITLE
Setting data not working when we include a template from string

### ISSUE THREAD

**Issue by Mewgan** [rybakit/twig-deferred-extension#5]
Is it possible to set data from a string template and include it after ?
```jinja
{# page.html.twig #}
{% extends "layout.html.twig" %}

{% block content %}
    {{ data.append('/js/page-header.js') }}

   {{ include(template_from_string(my_template)) }}
 
    {{ data.append('/js/page-footer.js') }}
{% endblock %}
```
```jinja
{# my_template #}
{{ data.append('/js/subpage1.js') }}
```

**Comment by rybakit** [comment]
@Mewgan @lachieh Sorry for the late reply. I tested the `template_from_string()` inclusion and didn't find any issues: https://github.com/rybakit/twig-extensions-deferred/blob/master/tests/Fixtures/include_from_string.test#L6-L7

**Comment by rybakit** [comment]
Closing the issue. Fill free to reopen it in case it still doesn't work for you.
